import { Inter } from 'next/font/google'
import './globals.css'
import './App.css'
import 'animate.css';
import 'react-tooltip/dist/react-tooltip.css'
import "react-datepicker/dist/react-datepicker.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id='root' style={{ height: '100vh' }}>
          {children}
        </div>
      </body>
    </html>
  )
}
